In [15]:
import kagglehub
import pandas as pd
# Download latest version
path = kagglehub.dataset_download("mohitkumar282/used-car-dataset")
data = pd.read_csv(f"{path}/used_car_dataset.csv")
print("Path to dataset files:", path)

Path to dataset files: C:\Users\cheth\.cache\kagglehub\datasets\mohitkumar282\used-car-dataset\versions\3

In [16]:
data.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000"
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000"
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999"
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000"
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000"

In [23]:
data.shape

(9582, 11)

In [24]:
data.dropna(inplace=True)

In [25]:
data.shape

(9535, 11)

In [26]:
import random

data['City']=random.choices(['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Hyderabad'], k=len(data))

In [27]:
data.shape

(9535, 12)

In [28]:
data.head()

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice,City
0,Honda,City,2001,23,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",Delhi
1,Toyota,Innova,2009,15,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",Bangalore
2,Volkswagen,VentoTest,2010,14,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",Bangalore
3,Maruti Suzuki,Swift,2017,7,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",Chennai
4,Maruti Suzuki,Baleno,2019,5,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",Bangalore

In [29]:
data.drop(['Age'], axis=1, inplace=True)

In [30]:
data.head()

,Brand,model,Year,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice,City
0,Honda,City,2001,"98,000 km",Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",Delhi
1,Toyota,Innova,2009,190000.0 km,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",Bangalore
2,Volkswagen,VentoTest,2010,"77,246 km",Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",Bangalore
3,Maruti Suzuki,Swift,2017,"83,500 km",Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",Chennai
4,Maruti Suzuki,Baleno,2019,"45,000 km",Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",Bangalore

In [31]:
data.drop(['PostedDate'],axis=1,inplace=True)

In [39]:
data['Description']=data['Brand'][0] + ' ' + data['model'][0] + ' ' + data['Year'].astype(str)[0] + ' model of ' + data['FuelType'][0] + ' variant driven for ' + data['kmDriven'].astype(str)[0] + ' in ' + data['City'][0]

In [55]:
data.head()

,brand,model,year,km_driven,transmission,owner,fuel_type,additional_info,price,city,description,car_id
0,Honda,City,2001,"98,000 km",Manual,second,Petrol,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",Delhi,Honda City 2001 model of Petrol variant driven...,84387
1,Toyota,Innova,2009,190000.0 km,Manual,second,Diesel,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",Bangalore,Honda City 2001 model of Petrol variant driven...,66027
2,Volkswagen,VentoTest,2010,"77,246 km",Manual,first,Diesel,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",Bangalore,Honda City 2001 model of Petrol variant driven...,23778
3,Maruti Suzuki,Swift,2017,"83,500 km",Manual,second,Diesel,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",Chennai,Honda City 2001 model of Petrol variant driven...,2237
4,Maruti Suzuki,Baleno,2019,"45,000 km",Automatic,first,Petrol,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",Bangalore,Honda City 2001 model of Petrol variant driven...,57340

In [47]:
data.rename(columns={'Brand':'brand','model':'model','Year':'year','FuelType':'fuel_type','kmDriven':'km_driven','City':'city','AskPrice':'price','Description':'description','AdditionInfo':'additional_info','Transmission':'transmission'}, inplace=True)

In [51]:
data['car_id']=random.sample(range(1000,100000),k=len(data))

In [54]:
data.rename(columns={'Owner':'owner'},inplace=True)

In [67]:
import os
from huggingface_hub import InferenceClient
from dotenv import load_dotenv
load_dotenv()
client = InferenceClient(
    provider="hf-inference",
    api_key=os.environ["hf_token"],
)
batch=32
for i in range(0, len(data), batch):
    batch_data = data['description'].iloc[i : i + batch].to_list()
    
    embeddings_list = client.feature_extraction(
        batch_data,
        model="microsoft/harrier-oss-v1-0.6b",
    )
    
    # 1. Convert the (32, 1024) array into a list of individual vectors
    embeddings_as_list = [v for v in embeddings_list]
    
    # 2. Get the specific indices for this batch
    batch_indices = data.index[i : i + len(embeddings_as_list)]
    
    # 3. Create a Series with the matching index to ensure perfect alignment
    data.loc[batch_indices, 'embeddings'] = pd.Series(embeddings_as_list, index=batch_indices)

C:\Users\cheth\AppData\Local\Temp\ipykernel_4940\3510261643.py:25: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)
 array([ 2.8016454e-02, -5.7057798e-02, -4.1489281e-38, ...,
         1.2856101e-02,  1.7870540e-02,  1.1063570e-02], dtype=float32)]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[batch_indices, 'embeddings'] = pd.Series(embeddings_as_list, index=batch_indices)

In [68]:
data.head()

,brand,model,year,km_driven,transmission,owner,fuel_type,additional_info,price,city,description,car_id,embeddings
0,Honda,City,2001,"98,000 km",Manual,second,Petrol,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",Delhi,Honda City 2001 model of Petrol variant driven...,84387,"[0.028016454, -0.057057798, -4.148928e-38, -0...."
1,Toyota,Innova,2009,190000.0 km,Manual,second,Diesel,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",Bangalore,Honda City 2001 model of Petrol variant driven...,66027,"[0.028016454, -0.057057798, -4.148928e-38, -0...."
2,Volkswagen,VentoTest,2010,"77,246 km",Manual,first,Diesel,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",Bangalore,Honda City 2001 model of Petrol variant driven...,23778,"[0.028016454, -0.057057798, -4.148928e-38, -0...."
3,Maruti Suzuki,Swift,2017,"83,500 km",Manual,second,Diesel,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",Chennai,Honda City 2001 model of Petrol variant driven...,2237,"[0.028016454, -0.057057798, -4.148928e-38, -0...."
4,Maruti Suzuki,Baleno,2019,"45,000 km",Automatic,first,Petrol,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",Bangalore,Honda City 2001 model of Petrol variant driven...,57340,"[0.028016454, -0.057057798, -4.148928e-38, -0...."

In [69]:
null_counts=data.isnull().sum()
print(null_counts)

brand              0
model              0
year               0
km_driven          0
transmission       0
owner              0
fuel_type          0
additional_info    0
price              0
city               0
description        0
car_id             0
embeddings         0
dtype: int64

In [ ]:
data.to_csv(f"{path}/used_car_dataset_with_embeddings.csv", index=False)

In [ ]:
data.head()

,brand,model,year,km_driven,transmission,owner,fuel_type,additional_info,price,city,description,car_id,embeddings
0,Honda,City,2001,"98,000 km",Manual,second,Petrol,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",Delhi,Honda City 2001 model of Petrol variant driven...,84387,"[0.028016454, -0.057057798, -4.148928e-38, -0...."
1,Toyota,Innova,2009,190000.0 km,Manual,second,Diesel,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",Bangalore,Honda City 2001 model of Petrol variant driven...,66027,"[0.028016454, -0.057057798, -4.148928e-38, -0...."
2,Volkswagen,VentoTest,2010,"77,246 km",Manual,first,Diesel,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",Bangalore,Honda City 2001 model of Petrol variant driven...,23778,"[0.028016454, -0.057057798, -4.148928e-38, -0...."
3,Maruti Suzuki,Swift,2017,"83,500 km",Manual,second,Diesel,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",Chennai,Honda City 2001 model of Petrol variant driven...,2237,"[0.028016454, -0.057057798, -4.148928e-38, -0...."
4,Maruti Suzuki,Baleno,2019,"45,000 km",Automatic,first,Petrol,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",Bangalore,Honda City 2001 model of Petrol variant driven...,57340,"[0.028016454, -0.057057798, -4.148928e-38, -0...."

:

In [6]:
import numpy as np

# Check the shape of the first embedding
vector = np.array(data['embeddings'].iloc[0])
print(f"Vector shape: {vector.shape}") 
# Should output (1024,) based on your model

Vector shape: ()

In [5]:
import pandas as pd
path="C:\\Users\\cheth\\.cache\\kagglehub\\datasets\\mohitkumar282\\used-car-dataset\\versions\\3"
data=pd.read_csv(f"{path}/used_car_dataset_with_embeddings.csv")
data.head()

,brand,model,year,km_driven,transmission,owner,fuel_type,additional_info,price,city,description,car_id,embeddings
0,Honda,City,2001,"98,000 km",Manual,second,Petrol,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",Delhi,Honda City 2001 model of Petrol variant driven...,84387,[ 2.8016454e-02 -5.7057798e-02 -4.1489281e-38 ...
1,Toyota,Innova,2009,190000.0 km,Manual,second,Diesel,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",Bangalore,Honda City 2001 model of Petrol variant driven...,66027,[ 2.8016454e-02 -5.7057798e-02 -4.1489281e-38 ...
2,Volkswagen,VentoTest,2010,"77,246 km",Manual,first,Diesel,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",Bangalore,Honda City 2001 model of Petrol variant driven...,23778,[ 2.8016454e-02 -5.7057798e-02 -4.1489281e-38 ...
3,Maruti Suzuki,Swift,2017,"83,500 km",Manual,second,Diesel,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",Chennai,Honda City 2001 model of Petrol variant driven...,2237,[ 2.8016454e-02 -5.7057798e-02 -4.1489281e-38 ...
4,Maruti Suzuki,Baleno,2019,"45,000 km",Automatic,first,Petrol,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",Bangalore,Honda City 2001 model of Petrol variant driven...,57340,[ 2.8016454e-02 -5.7057798e-02 -4.1489281e-38 ...

In [7]:
print(type(data['embeddings'].iloc[0]))
print(data['embeddings'].iloc[0][:5]) # Show first 5 numbers

<class 'str'>
[ 2.8

In [9]:
import ast

# 1. Convert the batch (NumPy array) into a list of lists (Python floats)
# .tolist() is crucial—it ensures commas are used and no truncation occurs
embeddings_as_list = embeddings_list.tolist() 

# 2. Assign directly to the slice
data.loc[batch_indices, 'embeddings'] = embeddings_as_list

# Convert the string representation back into a real list of floats
data['embeddings'] = data['embeddings'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Verify the fix
print(type(data['embeddings'].iloc[0])) # Should now be <class 'list'>
print(data['embeddings'].iloc[0][:3])    # Should show the first 3 numbers

NameError: name 'embeddings_list' is not defined

In [10]:
data.drop(['embeddings'],axis=1,inplace=True)

In [11]:
data.head()

,brand,model,year,km_driven,transmission,owner,fuel_type,additional_info,price,city,description,car_id
0,Honda,City,2001,"98,000 km",Manual,second,Petrol,"Honda City v teck in mint condition, valid gen...","₹ 1,95,000",Delhi,Honda City 2001 model of Petrol variant driven...,84387
1,Toyota,Innova,2009,190000.0 km,Manual,second,Diesel,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...","₹ 3,75,000",Bangalore,Honda City 2001 model of Petrol variant driven...,66027
2,Volkswagen,VentoTest,2010,"77,246 km",Manual,first,Diesel,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...","₹ 1,84,999",Bangalore,Honda City 2001 model of Petrol variant driven...,23778
3,Maruti Suzuki,Swift,2017,"83,500 km",Manual,second,Diesel,Maruti Suzuki Swift 2017 Diesel Good Condition,"₹ 5,65,000",Chennai,Honda City 2001 model of Petrol variant driven...,2237
4,Maruti Suzuki,Baleno,2019,"45,000 km",Automatic,first,Petrol,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol","₹ 6,85,000",Bangalore,Honda City 2001 model of Petrol variant driven...,57340

In [12]:
import os
import pandas as pd
from huggingface_hub import InferenceClient
from dotenv import load_dotenv

load_dotenv()

client = InferenceClient(
    provider="hf-inference",
    api_key=os.environ["hf_token"],
)

# Initialize the column as 'object' to store lists properly
data['embeddings'] = None
data['embeddings'] = data['embeddings'].astype(object)

batch = 32
for i in range(0, len(data), batch):
    batch_data = data['description'].iloc[i : i + batch].to_list()
    
    # 1. Fetch embeddings
    embeddings_list = client.feature_extraction(
        batch_data,
        model="microsoft/harrier-oss-v1-0.6b",
    )
    
    # 2. CRITICAL FIX: Convert NumPy array to a standard Python list of lists.
    # This ensures commas are present and prevents string truncation like "[2.8 ...]"
    if hasattr(embeddings_list, 'tolist'):
        embeddings_as_list = embeddings_list.tolist()
    else:
        embeddings_as_list = list(embeddings_list)
    
    # 3. Get indices and assign
    batch_indices = data.index[i : i + len(embeddings_as_list)]
    data.loc[batch_indices, 'embeddings'] = pd.Series(embeddings_as_list, index=batch_indices)

# 4. SAVE CORRECTLY: 
# Avoid .to_csv() as it will turn your vectors back into broken strings.
data.to_parquet('embeddings_results.parquet') 
print("Embeddings saved successfully to Parquet format.")

RemoteProtocolError: peer closed connection without sending complete message body (received 340138 bytes, expected 694593)

<class 'str'>
[ 2.8